### ISSUE TITLE
Todo: Computer Networks Unit-1

### ISSUE THREAD

**Issue by iShibi** [iShibi/Sem-6#1]
# Unit-1

- [ ] Introduction: Computer Networks and the Internet
- [ ] Overall view: As components and as services
- [x] What is a protocol
- [x] What is a network protocol
- [x] Access Networks
- [x] Physical Media
- [x] Circuit Switching
- [ ] Packet Switching
- [ ] Internet Backbone
- [ ] Delays:
  - [ ] Processing
  - [ ] Queuing
  - [ ] Transmission
  - [ ] Propagation
- [ ] The Layered Architecture: Protocol Layering
- [ ] The OSI Reference Model
- [ ] The TCP/IP protocol stack
- [ ] History of Computer Networking and the Internet
