### ISSUE TITLE
Todo: Compiler Design Unit-1

### ISSUE THREAD

**Issue by iShibi** [iShibi/Sem-6#2]
# Unit-1

- [ ] Compilers
  - [ ] Analysis  of  Source  Program
  - [ ] The  Phases  of  a  Compiler
  - [ ] Cousins  of  the  Compiler
  - [ ] The  grouping  of phases
  - [ ] Compiler-Construction tools
- [ ] Lexical analysis
  - [ ] The Role of Lexical Analyzer
  - [ ] Input Buffering
  - [ ] Specifications of Tokens
  - [ ] Recognition of Tokens
