### ISSUE TITLE
Todo: Full Stack Web Dev Unit-1

### ISSUE THREAD

**Issue by iShibi** [iShibi/Sem-6#3]
# Unit-1

- [ ] Basics of HTML
- [ ] Formatting and Fonts
- [ ] Commenting Code
- [ ] Color
- [ ] Hyperlink
- [ ] Lists
- [ ] Tables
- [ ] Images
- [ ] Forms
- [ ] XHTML
- [ ] Meta Tags
- [ ] Character Entities
- [ ] Frames and Frame Sets
- [ ] Browser Architecture and Website Structure
- [ ] Overview and Features of HTML5
